name: CI_telegram-informer

on: [push]


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }} # Если ваш ssh-ключ защищён фразой-паролем
        script: |
          git clone https://github.com/1kovalevskiy/telegram-informer.git || true
          cd /home/nikita/telegram-informer
          git pull
          cd /home/nikita/telegram-informer/infra
          sudo systemctl stop telegram-informer.service
          sudo docker-compose down
          sudo docker stop $(sudo docker ps -a -q) || true
          sudo docker-compose build --parallel
          sudo systemctl start telegram-informer.service
          sudo docker container prune -f

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
